/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by PostgreSDK.
 * Any manual changes will be overwritten on the next generation.
 *
 * To make changes, modify your schema or configuration and regenerate.
 */
import { BaseClient } from "./base-client";
import type { Where } from "./where-types";
import type { PaginatedResponse } from "./types/shared";
import type { InsertAuthors, UpdateAuthors, SelectAuthors } from "./types/authors";
import type { SelectBooks } from "./types/books";
import type { SelectTags } from "./types/tags";

/**
 * Client for authors table operations
 */
export class AuthorsClient extends BaseClient {
  private readonly resource = "/v1/authors";

  /**
   * Create a new authors record
   * @param data - The data to insert
   * @returns The created record
   */
  async create(data: InsertAuthors): Promise<SelectAuthors> {
    return this.post<SelectAuthors>(this.resource, data);
  }

  /**
   * Get a authors record by primary key
   * @param pk - The primary key value
   * @returns The record if found, null otherwise
   */
  async getByPk(pk: string): Promise<SelectAuthors | null> {
    const path = pk;
    return this.get<SelectAuthors | null>(`${this.resource}/${path}`);
  }

  /**
   * List authors records with pagination and filtering
   * @param params - Query parameters
   * @param params.where - Filter conditions using operators like $eq, $gt, $in, $like, etc.
   * @param params.orderBy - Column(s) to sort by
   * @param params.order - Sort direction(s): "asc" or "desc"
   * @param params.limit - Maximum number of records to return (default: 50, max: 100)
   * @param params.offset - Number of records to skip for pagination
   * @param params.include - Related records to include (see listWith* methods for typed includes)
   * @returns Paginated results with data, total count, and hasMore flag
   */
  async list(params?: {
    include?: any;
    limit?: number;
    offset?: number;
    where?: Where<SelectAuthors>;
    orderBy?: string | string[];
    order?: "asc" | "desc" | ("asc" | "desc")[];
  }): Promise<PaginatedResponse<SelectAuthors>> {
    return this.post<PaginatedResponse<SelectAuthors>>(`${this.resource}/list`, params ?? {});
  }

  /**
   * Update a authors record by primary key
   * @param pk - The primary key value
   * @param patch - Partial data to update
   * @returns The updated record if found, null otherwise
   */
  async update(pk: string, patch: UpdateAuthors): Promise<SelectAuthors | null> {
    const path = pk;
    return this.patch<SelectAuthors | null>(`${this.resource}/${path}`, patch);
  }

  /**
   * Delete a authors record by primary key
   * @param pk - The primary key value
   * @returns The deleted record if found, null otherwise
   */
  async delete(pk: string): Promise<SelectAuthors | null> {
    const path = pk;
    return this.del<SelectAuthors | null>(`${this.resource}/${path}`);
  }

  /**
   * List authors records with included related books
   * @param params - Query parameters (where, orderBy, order, limit, offset)
   * @returns Paginated results with nested books included
   */
  async listWithBooks(params?: Omit<{ limit?: number; offset?: number; where?: Where<SelectAuthors>; orderBy?: string | string[]; order?: "asc" | "desc" | ("asc" | "desc")[]; }, "include">): Promise<PaginatedResponse<SelectAuthors & { books: SelectBooks[] }>> {
    return this.post<PaginatedResponse<SelectAuthors & { books: SelectBooks[] }>>(`${this.resource}/list`, { ...params, include: {"books":true} });
  }

  /**
   * Get a authors record by primary key with included related books
   * @param pk - The primary key value
   * @returns The record with nested books if found, null otherwise
   */
  async getByPkWithBooks(pk: string): Promise<SelectAuthors & { books: SelectBooks[] } | null> {
    const results = await this.post<PaginatedResponse<SelectAuthors & { books: SelectBooks[] }>>(`${this.resource}/list`, {
      where: { id: pk },
      include: {"books":true},
      limit: 1
    });
    return (results.data[0] as SelectAuthors & { books: SelectBooks[] }) ?? null;
  }

  /**
   * List authors records with included related books -> tags
   * @param params - Query parameters (where, orderBy, order, limit, offset)
   * @returns Paginated results with nested books and tags included
   */
  async listWithBooksAndTags(params?: Omit<{ limit?: number; offset?: number; where?: Where<SelectAuthors>; orderBy?: string | string[]; order?: "asc" | "desc" | ("asc" | "desc")[]; }, "include">): Promise<PaginatedResponse<SelectAuthors & { books: (SelectBooks & { tags: SelectTags[] })[] }>> {
    return this.post<PaginatedResponse<SelectAuthors & { books: (SelectBooks & { tags: SelectTags[] })[] }>>(`${this.resource}/list`, { ...params, include: {"books":{"tags":true}} });
  }

  /**
   * Get a authors record by primary key with included related books -> tags
   * @param pk - The primary key value
   * @returns The record with nested books and tags if found, null otherwise
   */
  async getByPkWithBooksAndTags(pk: string): Promise<SelectAuthors & { books: (SelectBooks & { tags: SelectTags[] })[] } | null> {
    const results = await this.post<PaginatedResponse<SelectAuthors & { books: (SelectBooks & { tags: SelectTags[] })[] }>>(`${this.resource}/list`, {
      where: { id: pk },
      include: {"books":{"tags":true}},
      limit: 1
    });
    return (results.data[0] as SelectAuthors & { books: (SelectBooks & { tags: SelectTags[] })[] }) ?? null;
  }
}
