/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by PostgreSDK.
 * Any manual changes will be overwritten on the next generation.
 *
 * To make changes, modify your schema or configuration and regenerate.
 */
import { BaseClient } from "./base-client";
import type { Where } from "./where-types";
import type { PaginatedResponse } from "./types/shared";
import type { InsertBookTags, UpdateBookTags, SelectBookTags } from "./types/book_tags";


/**
 * Client for book_tags table operations
 */
export class BookTagsClient extends BaseClient {
  private readonly resource = "/v1/book_tags";

  /**
   * Create a new book_tags record
   * @param data - The data to insert
   * @returns The created record
   */
  async create(data: InsertBookTags): Promise<SelectBookTags> {
    return this.post<SelectBookTags>(this.resource, data);
  }

  /**
   * Get a book_tags record by primary key
   * @param pk - The primary key values
   * @returns The record if found, null otherwise
   */
  async getByPk(pk: { book_id: string; tag_id: string }): Promise<SelectBookTags | null> {
    const path = pk.book_id + "/" + pk.tag_id;
    return this.get<SelectBookTags | null>(`${this.resource}/${path}`);
  }

  /**
   * List book_tags records with pagination and filtering
   * @param params - Query parameters
   * @param params.where - Filter conditions using operators like $eq, $gt, $in, $like, etc.
   * @param params.orderBy - Column(s) to sort by
   * @param params.order - Sort direction(s): "asc" or "desc"
   * @param params.limit - Maximum number of records to return (default: 50, max: 1000)
   * @param params.offset - Number of records to skip for pagination
   * @param params.include - Related records to include (see listWith* methods for typed includes)
   * @returns Paginated results with data, total count, and hasMore flag
   */
  async list(params?: {
    include?: any;
    limit?: number;
    offset?: number;
    where?: Where<SelectBookTags>;
    orderBy?: string | string[];
    order?: "asc" | "desc" | ("asc" | "desc")[];
  }): Promise<PaginatedResponse<SelectBookTags>> {
    return this.post<PaginatedResponse<SelectBookTags>>(`${this.resource}/list`, params ?? {});
  }

  /**
   * Update a book_tags record by primary key
   * @param pk - The primary key values
   * @param patch - Partial data to update
   * @returns The updated record if found, null otherwise
   */
  async update(pk: { book_id: string; tag_id: string }, patch: UpdateBookTags): Promise<SelectBookTags | null> {
    const path = pk.book_id + "/" + pk.tag_id;
    return this.patch<SelectBookTags | null>(`${this.resource}/${path}`, patch);
  }

  /**
   * Delete a book_tags record by primary key
   * @param pk - The primary key values
   * @returns The deleted record if found, null otherwise
   */
  async delete(pk: { book_id: string; tag_id: string }): Promise<SelectBookTags | null> {
    const path = pk.book_id + "/" + pk.tag_id;
    return this.del<SelectBookTags | null>(`${this.resource}/${path}`);
  }
}
