/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by PostgreSDK.
 * Any manual changes will be overwritten on the next generation.
 *
 * To make changes, modify your schema or configuration and regenerate.
 */
import { BaseClient, type AuthConfig } from "./base-client";
import { AuthorsClient } from "./authors";
import { BookTagsClient } from "./book_tags";
import { BooksClient } from "./books";
import { ProductsClient } from "./products";
import { TagsClient } from "./tags";
import { UsersClient } from "./users";

export type { AuthConfig, HeaderMap, AuthHeadersProvider } from "./base-client";

/**
 * Main SDK class that provides access to all table clients
 */
export class SDK {
  public authors: AuthorsClient;
  public book_tags: BookTagsClient;
  public books: BooksClient;
  public products: ProductsClient;
  public tags: TagsClient;
  public users: UsersClient;

  constructor(cfg: { baseUrl: string; fetch?: typeof fetch; auth?: AuthConfig }) {
    const f = cfg.fetch ?? fetch;
    this.authors = new AuthorsClient(cfg.baseUrl, f, cfg.auth);
    this.book_tags = new BookTagsClient(cfg.baseUrl, f, cfg.auth);
    this.books = new BooksClient(cfg.baseUrl, f, cfg.auth);
    this.products = new ProductsClient(cfg.baseUrl, f, cfg.auth);
    this.tags = new TagsClient(cfg.baseUrl, f, cfg.auth);
    this.users = new UsersClient(cfg.baseUrl, f, cfg.auth);
  }
}

export { BaseClient } from "./base-client";

// Include specification types for custom queries
export type {
  AuthorsIncludeSpec,
  BookTagsIncludeSpec,
  BooksIncludeSpec,
  ProductsIncludeSpec,
  TagsIncludeSpec,
  UsersIncludeSpec,
} from "./include-spec";

// Zod schemas for form validation
export { InsertAuthorsSchema, UpdateAuthorsSchema } from "./zod/authors";
export { InsertBookTagsSchema, UpdateBookTagsSchema } from "./zod/book_tags";
export { InsertBooksSchema, UpdateBooksSchema } from "./zod/books";
export { InsertProductsSchema, UpdateProductsSchema } from "./zod/products";
export { InsertTagsSchema, UpdateTagsSchema } from "./zod/tags";
export { InsertUsersSchema, UpdateUsersSchema } from "./zod/users";

// Zod schemas for query parameters
export { PaginationParamsSchema } from "./params/shared";
export { AuthorsPkSchema, AuthorsListParamsSchema, AuthorsOrderParamsSchema } from "./params/authors";
export { BookTagsPkSchema, BookTagsListParamsSchema, BookTagsOrderParamsSchema } from "./params/book_tags";
export { BooksPkSchema, BooksListParamsSchema, BooksOrderParamsSchema } from "./params/books";
export { ProductsPkSchema, ProductsListParamsSchema, ProductsOrderParamsSchema } from "./params/products";
export { TagsPkSchema, TagsListParamsSchema, TagsOrderParamsSchema } from "./params/tags";
export { UsersPkSchema, UsersListParamsSchema, UsersOrderParamsSchema } from "./params/users";

// Table types (Select, Insert, Update)
export type { InsertAuthors, UpdateAuthors, SelectAuthors } from "./types/authors";
export type { InsertBookTags, UpdateBookTags, SelectBookTags } from "./types/book_tags";
export type { InsertBooks, UpdateBooks, SelectBooks } from "./types/books";
export type { InsertProducts, UpdateProducts, SelectProducts } from "./types/products";
export type { InsertTags, UpdateTags, SelectTags } from "./types/tags";
export type { InsertUsers, UpdateUsers, SelectUsers } from "./types/users";

// Shared types
export type { PaginatedResponse } from "./types/shared";
