/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by PostgreSDK.
 * Any manual changes will be overwritten on the next generation.
 *
 * To make changes, modify your schema or configuration and regenerate.
 */
import { BaseClient } from "./base-client";
import type { Where } from "./where-types";
import type { PaginatedResponse } from "./types/shared";
import type { InsertTags, UpdateTags, SelectTags } from "./types/tags";
import type { SelectBooks } from "./types/books";
import type { SelectAuthors } from "./types/authors";

/**
 * Client for tags table operations
 */
export class TagsClient extends BaseClient {
  private readonly resource = "/v1/tags";

  /**
   * Create a new tags record
   * @param data - The data to insert
   * @returns The created record
   */
  async create(data: InsertTags): Promise<SelectTags> {
    return this.post<SelectTags>(this.resource, data);
  }

  /**
   * Get a tags record by primary key
   * @param pk - The primary key value
   * @returns The record if found, null otherwise
   */
  async getByPk(pk: string): Promise<SelectTags | null> {
    const path = pk;
    return this.get<SelectTags | null>(`${this.resource}/${path}`);
  }

  /**
   * List tags records with pagination and filtering
   * @param params - Query parameters
   * @param params.where - Filter conditions using operators like $eq, $gt, $in, $like, etc.
   * @param params.orderBy - Column(s) to sort by
   * @param params.order - Sort direction(s): "asc" or "desc"
   * @param params.limit - Maximum number of records to return (default: 50, max: 100)
   * @param params.offset - Number of records to skip for pagination
   * @param params.include - Related records to include (see listWith* methods for typed includes)
   * @returns Paginated results with data, total count, and hasMore flag
   */
  async list(params?: {
    include?: any;
    limit?: number;
    offset?: number;
    where?: Where<SelectTags>;
    orderBy?: string | string[];
    order?: "asc" | "desc" | ("asc" | "desc")[];
  }): Promise<PaginatedResponse<SelectTags>> {
    return this.post<PaginatedResponse<SelectTags>>(`${this.resource}/list`, params ?? {});
  }

  /**
   * Update a tags record by primary key
   * @param pk - The primary key value
   * @param patch - Partial data to update
   * @returns The updated record if found, null otherwise
   */
  async update(pk: string, patch: UpdateTags): Promise<SelectTags | null> {
    const path = pk;
    return this.patch<SelectTags | null>(`${this.resource}/${path}`, patch);
  }

  /**
   * Delete a tags record by primary key
   * @param pk - The primary key value
   * @returns The deleted record if found, null otherwise
   */
  async delete(pk: string): Promise<SelectTags | null> {
    const path = pk;
    return this.del<SelectTags | null>(`${this.resource}/${path}`);
  }

  /**
   * List tags records with included related books
   * @param params - Query parameters (where, orderBy, order, limit, offset)
   * @returns Paginated results with nested books included
   */
  async listWithBooks(params?: Omit<{ limit?: number; offset?: number; where?: Where<SelectTags>; orderBy?: string | string[]; order?: "asc" | "desc" | ("asc" | "desc")[]; }, "include">): Promise<PaginatedResponse<SelectTags & { books: SelectBooks[] }>> {
    return this.post<PaginatedResponse<SelectTags & { books: SelectBooks[] }>>(`${this.resource}/list`, { ...params, include: {"books":true} });
  }

  /**
   * Get a tags record by primary key with included related books
   * @param pk - The primary key value
   * @returns The record with nested books if found, null otherwise
   */
  async getByPkWithBooks(pk: string): Promise<SelectTags & { books: SelectBooks[] } | null> {
    const results = await this.post<PaginatedResponse<SelectTags & { books: SelectBooks[] }>>(`${this.resource}/list`, {
      where: { id: pk },
      include: {"books":true},
      limit: 1
    });
    return (results.data[0] as SelectTags & { books: SelectBooks[] }) ?? null;
  }

  /**
   * List tags records with included related books -> author
   * @param params - Query parameters (where, orderBy, order, limit, offset)
   * @returns Paginated results with nested books and author included
   */
  async listWithBooksAndAuthor(params?: Omit<{ limit?: number; offset?: number; where?: Where<SelectTags>; orderBy?: string | string[]; order?: "asc" | "desc" | ("asc" | "desc")[]; }, "include">): Promise<PaginatedResponse<SelectTags & { books: (SelectBooks & { author: SelectAuthors })[] }>> {
    return this.post<PaginatedResponse<SelectTags & { books: (SelectBooks & { author: SelectAuthors })[] }>>(`${this.resource}/list`, { ...params, include: {"books":{"author":true}} });
  }

  /**
   * Get a tags record by primary key with included related books -> author
   * @param pk - The primary key value
   * @returns The record with nested books and author if found, null otherwise
   */
  async getByPkWithBooksAndAuthor(pk: string): Promise<SelectTags & { books: (SelectBooks & { author: SelectAuthors })[] } | null> {
    const results = await this.post<PaginatedResponse<SelectTags & { books: (SelectBooks & { author: SelectAuthors })[] }>>(`${this.resource}/list`, {
      where: { id: pk },
      include: {"books":{"author":true}},
      limit: 1
    });
    return (results.data[0] as SelectTags & { books: (SelectBooks & { author: SelectAuthors })[] }) ?? null;
  }
}
