/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by PostgreSDK.
 * Any manual changes will be overwritten on the next generation.
 *
 * To make changes, modify your schema or configuration and regenerate.
 */
import { BaseClient } from "./base-client";
import type { Where } from "./where-types";
import type { PaginatedResponse } from "./types/shared";
import type { InsertUsers, UpdateUsers, SelectUsers } from "./types/users";


/**
 * Client for users table operations
 */
export class UsersClient extends BaseClient {
  private readonly resource = "/v1/users";

  /**
   * Create a new users record
   * @param data - The data to insert
   * @returns The created record
   */
  async create(data: InsertUsers): Promise<SelectUsers> {
    return this.post<SelectUsers>(this.resource, data);
  }

  /**
   * Get a users record by primary key
   * @param pk - The primary key value
   * @returns The record if found, null otherwise
   */
  async getByPk(pk: string): Promise<SelectUsers | null> {
    const path = pk;
    return this.get<SelectUsers | null>(`${this.resource}/${path}`);
  }

  /**
   * List users records with pagination and filtering
   * @param params - Query parameters
   * @param params.where - Filter conditions using operators like $eq, $gt, $in, $like, etc.
   * @param params.orderBy - Column(s) to sort by
   * @param params.order - Sort direction(s): "asc" or "desc"
   * @param params.limit - Maximum number of records to return (default: 50, max: 1000)
   * @param params.offset - Number of records to skip for pagination
   * @param params.include - Related records to include (see listWith* methods for typed includes)
   * @returns Paginated results with data, total count, and hasMore flag
   */
  async list(params?: {
    include?: any;
    limit?: number;
    offset?: number;
    where?: Where<SelectUsers>;
    orderBy?: string | string[];
    order?: "asc" | "desc" | ("asc" | "desc")[];
  }): Promise<PaginatedResponse<SelectUsers>> {
    return this.post<PaginatedResponse<SelectUsers>>(`${this.resource}/list`, params ?? {});
  }

  /**
   * Update a users record by primary key
   * @param pk - The primary key value
   * @param patch - Partial data to update
   * @returns The updated record if found, null otherwise
   */
  async update(pk: string, patch: UpdateUsers): Promise<SelectUsers | null> {
    const path = pk;
    return this.patch<SelectUsers | null>(`${this.resource}/${path}`, patch);
  }

  /**
   * Delete a users record by primary key
   * @param pk - The primary key value
   * @returns The deleted record if found, null otherwise
   */
  async delete(pk: string): Promise<SelectUsers | null> {
    const path = pk;
    return this.del<SelectUsers | null>(`${this.resource}/${path}`);
  }
}
