/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by PostgreSDK.
 * Any manual changes will be overwritten on the next generation.
 *
 * To make changes, modify your schema or configuration and regenerate.
 */

/**
 * Type for inserting a new authors record.
 * Fields with defaults or nullable columns are optional.
 */
export type InsertAuthors = {
  id?: string;
  name: string;
};

/**
 * Type for updating an existing authors record.
 * All fields are optional, allowing partial updates.
 */
export type UpdateAuthors = Partial<InsertAuthors>;

/**
 * Type representing a authors record from the database.
 * All fields are included as returned by SELECT queries.
 */
export type SelectAuthors = {
  id: string;
  name: string;
};
