/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by PostgreSDK.
 * Any manual changes will be overwritten on the next generation.
 *
 * To make changes, modify your schema or configuration and regenerate.
 */

/**
 * Type for inserting a new book_tags record.
 * Fields with defaults or nullable columns are optional.
 */
export type InsertBookTags = {
  book_id: string;
  tag_id: string;
};

/**
 * Type for updating an existing book_tags record.
 * All fields are optional, allowing partial updates.
 */
export type UpdateBookTags = Partial<InsertBookTags>;

/**
 * Type representing a book_tags record from the database.
 * All fields are included as returned by SELECT queries.
 */
export type SelectBookTags = {
  book_id: string;
  tag_id: string;
};
