/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by PostgreSDK.
 * Any manual changes will be overwritten on the next generation.
 *
 * To make changes, modify your schema or configuration and regenerate.
 */

/**
 * Type for inserting a new products record.
 * Fields with defaults or nullable columns are optional.
 */
export type InsertProducts = {
  id?: string;
  name: string;
  status?: "draft" | "published" | "archived";
  priority: "low" | "medium" | "high" | "critical";
  tags?: ("admin" | "moderator" | "user" | "guest")[] | null;
};

/**
 * Type for updating an existing products record.
 * All fields are optional, allowing partial updates.
 */
export type UpdateProducts = Partial<InsertProducts>;

/**
 * Type representing a products record from the database.
 * All fields are included as returned by SELECT queries.
 */
export type SelectProducts = {
  id: string;
  name: string;
  status: "draft" | "published" | "archived";
  priority: "low" | "medium" | "high" | "critical";
  tags: ("admin" | "moderator" | "user" | "guest")[] | null;
};
