/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by PostgreSDK.
 * Any manual changes will be overwritten on the next generation.
 *
 * To make changes, modify your schema or configuration and regenerate.
 */

/**
 * Type for inserting a new users record.
 * Fields with defaults or nullable columns are optional.
 */
export type InsertUsers = {
  id?: string;
  email: string;
  role?: "admin" | "moderator" | "user" | "guest";
  backup_role?: "admin" | "moderator" | "user" | "guest" | null;
};

/**
 * Type for updating an existing users record.
 * All fields are optional, allowing partial updates.
 */
export type UpdateUsers = Partial<InsertUsers>;

/**
 * Type representing a users record from the database.
 * All fields are included as returned by SELECT queries.
 */
export type SelectUsers = {
  id: string;
  email: string;
  role: "admin" | "moderator" | "user" | "guest";
  backup_role: "admin" | "moderator" | "user" | "guest" | null;
};
