/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by PostgreSDK.
 * Any manual changes will be overwritten on the next generation.
 *
 * To make changes, modify your schema or configuration and regenerate.
 */

export const SDK_MANIFEST = {
  version: "1.0.0",
  generated: "2025-11-20T22:28:26.797Z",
  files: {}
};
