/* Emits TypeScript types (Insert/Update/Select) for each table. */
import type { Table } from "./introspect";

function tsTypeFor(pgType: string, opts: { numericMode: "string" | "number" }, enums: Record<string, string[]>): string {
  const t = pgType.toLowerCase();

  // Check if this is an enum type
  if (enums[t]) {
    return enums[t].map(v => `"${v}"`).join(" | ");
  }

  if (t.startsWith("_")) return `(${tsTypeFor(t.slice(1), opts, enums)})[]`;
  if (t === "uuid") return "string";
  if (t === "bool" || t === "boolean") return "boolean";
  if (t === "int2" || t === "int4" || t === "int8" || t === "float4" || t === "float8" || t === "numeric") {
    return opts.numericMode === "number" ? "number" : "string";
  }
  if (t === "date" || t.startsWith("timestamp")) return "string";
  if (t === "json" || t === "jsonb") return "unknown";
  if (t === "vector" || t === "halfvec" || t === "sparsevec" || t === "bit") return "number[]";
  return "string";
}

function isJsonbType(pgType: string): boolean {
  const t = pgType.toLowerCase();
  return t === "json" || t === "jsonb";
}

const pascal = (s: string) =>
  s
    .split(/[_\s-]+/)
    .map((w) => (w?.[0] ? w[0].toUpperCase() + w.slice(1) : ""))
    .join("");

export function emitTypes(table: Table, opts: { numericMode: "string" | "number" }, enums: Record<string, string[]>) {
  const Type = pascal(table.name);

  // Check if table has any JSONB columns
  const hasJsonbColumns = table.columns.some(col => isJsonbType(col.pgType));

  const insertFields = table.columns
    .map((col) => {
      const base = tsTypeFor(col.pgType, opts, enums);
      const optional = col.hasDefault || col.nullable ? "?" : "";
      const valueType = col.nullable ? `${base} | null` : base;
      return `  ${col.name}${optional}: ${valueType};`;
    })
    .join("\n");

  const selectFields = table.columns
    .map((col) => {
      const base = tsTypeFor(col.pgType, opts, enums);
      const valueType = col.nullable ? `${base} | null` : base;
      return `  ${col.name}: ${valueType};`;
    })
    .join("\n");

  // Generate base types (internal, used for generics)
  const baseInsertType = `type _Insert${Type}Base = {
${insertFields}
};`;

  const baseSelectType = `type _Select${Type}Base = {
${selectFields}
};`;

  // Generate public types - generic if table has JSONB columns
  if (hasJsonbColumns) {
    return `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by PostgreSDK.
 * Any manual changes will be overwritten on the next generation.
 *
 * To make changes, modify your schema or configuration and regenerate.
 */

${baseInsertType}

${baseSelectType}

/**
 * Type for inserting a new ${table.name} record.
 * Fields with defaults or nullable columns are optional.
 *
 * Generic parameter TJsonb allows overriding JSONB column types:
 * @example Insert${Type}<{ metadata: MyMetadataType }>
 */
export type Insert${Type}<TJsonb extends Partial<_Insert${Type}Base> = {}> =
  {} extends TJsonb
    ? _Insert${Type}Base
    : Omit<_Insert${Type}Base, keyof TJsonb> & TJsonb;

/**
 * Type for updating an existing ${table.name} record.
 * All fields are optional, allowing partial updates.
 *
 * Generic parameter TJsonb allows overriding JSONB column types:
 * @example Update${Type}<{ metadata: MyMetadataType }>
 */
export type Update${Type}<TJsonb extends Partial<_Select${Type}Base> = {}> =
  {} extends TJsonb
    ? Partial<_Insert${Type}Base>
    : Partial<Omit<_Insert${Type}Base, keyof TJsonb> & TJsonb>;

/**
 * Type representing a ${table.name} record from the database.
 * All fields are included as returned by SELECT queries.
 *
 * Generic parameter TJsonb allows overriding JSONB column types:
 * @example Select${Type}<{ metadata: MyMetadataType }>
 */
export type Select${Type}<TJsonb extends Partial<_Select${Type}Base> = {}> =
  {} extends TJsonb
    ? _Select${Type}Base
    : Omit<_Select${Type}Base, keyof TJsonb> & TJsonb;
`;
  }

  // Non-JSONB tables - simple, non-generic types
  return `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by PostgreSDK.
 * Any manual changes will be overwritten on the next generation.
 *
 * To make changes, modify your schema or configuration and regenerate.
 */

/**
 * Type for inserting a new ${table.name} record.
 * Fields with defaults or nullable columns are optional.
 */
export type Insert${Type} = {
${insertFields}
};

/**
 * Type for updating an existing ${table.name} record.
 * All fields are optional, allowing partial updates.
 */
export type Update${Type} = Partial<Insert${Type}>;

/**
 * Type representing a ${table.name} record from the database.
 * All fields are included as returned by SELECT queries.
 */
export type Select${Type} = {
${selectFields}
};
`;
}
