/**
 * Emits WHERE clause type utilities for type-safe filtering
 */

export function emitWhereTypes() {
  return `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by PostgreSDK.
 * Any manual changes will be overwritten on the next generation.
 *
 * To make changes, modify your schema or configuration and regenerate.
 */

/**
 * Deep partial type for JSONB contains operator
 */
type DeepPartial<T> = T extends object ? {
  [P in keyof T]?: DeepPartial<T[P]>;
} : T;

/**
 * JSONB path query configuration
 */
type JsonbPathQuery = {
  /** Array of keys to traverse (e.g., ['user', 'preferences', 'theme']) */
  path: string[];
  /** Operator to apply to the value at the path (defaults to '$eq') */
  operator?: '$eq' | '$ne' | '$gt' | '$gte' | '$lt' | '$lte' | '$like' | '$ilike';
  /** Value to compare against */
  value: any;
};

/**
 * WHERE clause operators for filtering
 */
export type WhereOperator<T> = {
  /** Equal to */
  $eq?: T;
  /** Not equal to */
  $ne?: T;
  /** Greater than */
  $gt?: T;
  /** Greater than or equal to */
  $gte?: T;
  /** Less than */
  $lt?: T;
  /** Less than or equal to */
  $lte?: T;
  /** In array */
  $in?: T[];
  /** Not in array */
  $nin?: T[];
  /** LIKE pattern match (strings only) */
  $like?: T extends string ? string : never;
  /** Case-insensitive LIKE (strings only) */
  $ilike?: T extends string ? string : never;
  /** IS NULL */
  $is?: null;
  /** IS NOT NULL */
  $isNot?: null;

  // JSONB operators (only available for object/unknown types)
  /** JSONB contains (@>) - check if column contains the specified JSON structure */
  $jsonbContains?: T extends object | unknown ? (unknown extends T ? any : DeepPartial<T>) : never;
  /** JSONB contained by (<@) - check if column is contained by the specified JSON */
  $jsonbContainedBy?: T extends object | unknown ? any : never;
  /** JSONB has key (?) - check if top-level key exists */
  $jsonbHasKey?: T extends object | unknown ? string : never;
  /** JSONB has any keys (?|) - check if any of the specified keys exist */
  $jsonbHasAnyKeys?: T extends object | unknown ? string[] : never;
  /** JSONB has all keys (?&) - check if all of the specified keys exist */
  $jsonbHasAllKeys?: T extends object | unknown ? string[] : never;
  /** JSONB path query - query nested values. For multiple paths on same column, use $and */
  $jsonbPath?: T extends object | unknown ? JsonbPathQuery : never;
};

/**
 * WHERE condition - can be a direct value or an operator object
 */
export type WhereCondition<T> = T | WhereOperator<T>;

/**
 * Field-level WHERE conditions (without logical operators)
 */
export type WhereFieldConditions<T> = {
  [K in keyof T]?: WhereCondition<T[K]>;
};

/**
 * WHERE clause type with support for $or/$and logical operators (2 levels max)
 *
 * Examples:
 * - Basic OR: { $or: [{ name: 'Alice' }, { name: 'Bob' }] }
 * - Mixed AND + OR: { status: 'active', $or: [{ age: { $gt: 65 } }, { age: { $lt: 18 } }] }
 * - Nested (2 levels): { $and: [{ $or: [{ name: 'Alice' }, { name: 'Bob' }] }, { status: 'active' }] }
 */
export type Where<T> = WhereFieldConditions<T> & {
  /** OR - at least one condition must be true */
  $or?: (WhereFieldConditions<T>)[];
  /** AND - all conditions must be true (alternative to implicit root-level AND) */
  $and?: (WhereFieldConditions<T> | { $or?: WhereFieldConditions<T>[] })[];
};
`;
}
