/**
 * Emits WHERE clause type utilities for type-safe filtering
 */

export function emitWhereTypes() {
  return `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by PostgreSDK.
 * Any manual changes will be overwritten on the next generation.
 *
 * To make changes, modify your schema or configuration and regenerate.
 */

/**
 * WHERE clause operators for filtering
 */
export type WhereOperator<T> = {
  /** Equal to */
  $eq?: T;
  /** Not equal to */
  $ne?: T;
  /** Greater than */
  $gt?: T;
  /** Greater than or equal to */
  $gte?: T;
  /** Less than */
  $lt?: T;
  /** Less than or equal to */
  $lte?: T;
  /** In array */
  $in?: T[];
  /** Not in array */
  $nin?: T[];
  /** LIKE pattern match (strings only) */
  $like?: T extends string ? string : never;
  /** Case-insensitive LIKE (strings only) */
  $ilike?: T extends string ? string : never;
  /** IS NULL */
  $is?: null;
  /** IS NOT NULL */
  $isNot?: null;
};

/**
 * WHERE condition - can be a direct value or an operator object
 */
export type WhereCondition<T> = T | WhereOperator<T>;

/**
 * Field-level WHERE conditions (without logical operators)
 */
export type WhereFieldConditions<T> = {
  [K in keyof T]?: WhereCondition<T[K]>;
};

/**
 * WHERE clause type with support for $or/$and logical operators (2 levels max)
 *
 * Examples:
 * - Basic OR: { $or: [{ name: 'Alice' }, { name: 'Bob' }] }
 * - Mixed AND + OR: { status: 'active', $or: [{ age: { $gt: 65 } }, { age: { $lt: 18 } }] }
 * - Nested (2 levels): { $and: [{ $or: [{ name: 'Alice' }, { name: 'Bob' }] }, { status: 'active' }] }
 */
export type Where<T> = WhereFieldConditions<T> & {
  /** OR - at least one condition must be true */
  $or?: (WhereFieldConditions<T>)[];
  /** AND - all conditions must be true (alternative to implicit root-level AND) */
  $and?: (WhereFieldConditions<T> | { $or?: WhereFieldConditions<T>[] })[];
};
`;
}
