/* Emits TypeScript types (Insert/Update/Select) for each table. */
import type { Table } from "./introspect";

function tsTypeFor(pgType: string, opts: { numericMode: "string" | "number" }, enums: Record<string, string[]>): string {
  const t = pgType.toLowerCase();

  // Check if this is an enum type
  if (enums[t]) {
    return enums[t].map(v => `"${v}"`).join(" | ");
  }

  if (t.startsWith("_")) return `(${tsTypeFor(t.slice(1), opts, enums)})[]`;
  if (t === "uuid") return "string";
  if (t === "bool" || t === "boolean") return "boolean";
  if (t === "int2" || t === "int4" || t === "int8" || t === "float4" || t === "float8" || t === "numeric") {
    return opts.numericMode === "number" ? "number" : "string";
  }
  if (t === "date" || t.startsWith("timestamp")) return "string";
  if (t === "json" || t === "jsonb") return "unknown";
  return "string";
}

const pascal = (s: string) =>
  s
    .split(/[_\s-]+/)
    .map((w) => (w?.[0] ? w[0].toUpperCase() + w.slice(1) : ""))
    .join("");

export function emitTypes(table: Table, opts: { numericMode: "string" | "number" }, enums: Record<string, string[]>) {
  const Type = pascal(table.name);

  const insertFields = table.columns
    .map((col) => {
      const base = tsTypeFor(col.pgType, opts, enums);
      const optional = col.hasDefault || col.nullable ? "?" : "";
      const valueType = col.nullable ? `${base} | null` : base;
      return `  ${col.name}${optional}: ${valueType};`;
    })
    .join("\n");

  const selectFields = table.columns
    .map((col) => {
      const base = tsTypeFor(col.pgType, opts, enums);
      const valueType = col.nullable ? `${base} | null` : base;
      return `  ${col.name}: ${valueType};`;
    })
    .join("\n");

  return `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by PostgreSDK.
 * Any manual changes will be overwritten on the next generation.
 *
 * To make changes, modify your schema or configuration and regenerate.
 */
export type Insert${Type} = {
${insertFields}
};

export type Update${Type} = Partial<Insert${Type}>;

export type Select${Type} = {
${selectFields}
};
`;
}
