import type { Table, Model } from "./introspect";
import type { Graph } from "./rel-classify";
import { pascal } from "./utils";
import { generateIncludeMethods } from "./emit-include-methods";

/**
 * Check if a PostgreSQL type is a vector type (vector, halfvec, sparsevec, bit)
 */
function isVectorType(pgType: string): boolean {
  const t = pgType.toLowerCase();
  return t === "vector" || t === "halfvec" || t === "sparsevec" || t === "bit";
}

export function emitClient(
  table: Table,
  graph: Graph,
  opts: {
    useJsExtensions?: boolean;
    includeMethodsDepth?: number;
    skipJunctionTables?: boolean;
  },
  model?: Model
) {
  const Type = pascal(table.name);
  const ext = opts.useJsExtensions ? ".js" : "";

  // Check if table has any vector columns
  const hasVectorColumns = table.columns.some(c => isVectorType(c.pgType));

  // Normalize PKs
  const pkCols: string[] = Array.isArray((table as any).pk)
    ? (table as any).pk
    : (table as any).pk
    ? [(table as any).pk]
    : [];
  const safePk = pkCols.length ? pkCols : ["id"];
  const hasCompositePk = safePk.length > 1;

  const pkType = hasCompositePk ? `{ ${safePk.map((c) => `${c}: string`).join("; ")} }` : `string`;
  const pkPathExpr = hasCompositePk ? safePk.map((c) => `pk.${c}`).join(` + "/" + `) : `pk`;

  // Generate include methods
  const allTables = model ? Object.values(model.tables) : undefined;
  const includeMethods = generateIncludeMethods(table, graph, {
    maxDepth: opts.includeMethodsDepth ?? 2,
    skipJunctionTables: opts.skipJunctionTables ?? true
  }, allTables);

  // Build import for types needed by include methods
  const importedTypes = new Set<string>();
  importedTypes.add(table.name); // Always need base type
  
  for (const method of includeMethods) {
    for (const target of method.targets) {
      importedTypes.add(target);
    }
  }

  // Generate type imports - base types for this table
  const typeImports = `import type { Insert${Type}, Update${Type}, Select${Type} } from "./types/${table.name}${ext}";`;
  
  // If we have includes from other tables, we need those types too
  const otherTableImports: string[] = [];
  for (const target of Array.from(importedTypes)) {
    if (target !== table.name) {
      otherTableImports.push(`import type { Select${pascal(target)} } from "./types/${target}${ext}";`);
    }
  }

  // Generate include method implementations
  let includeMethodsCode = "";
  for (const method of includeMethods) {
    const isGetByPk = method.name.startsWith("getByPk");
    const baseParams = isGetByPk ? "" : `params?: Omit<{ limit?: number; offset?: number; where?: Where<Select${Type}>; orderBy?: string | string[]; order?: "asc" | "desc" | ("asc" | "desc")[]; }, "include">`;

    // Generate JSDoc description
    const relationshipDesc = method.path.map((p, i) => {
      const isLast = i === method.path.length - 1;
      const relation = method.isMany[i] ? "many" : "one";
      return isLast ? p : `${p} -> `;
    }).join('');

    if (isGetByPk) {
      // For getByPk with includes, we use the list endpoint with a where clause
      const pkWhere = hasCompositePk
        ? `{ ${safePk.map(col => `${col}: pk.${col}`).join(", ")} }`
        : `{ ${safePk[0] || 'id'}: pk }`;

      // Extract the base return type (without the "| null" part)
      const baseReturnType = method.returnType.replace(" | null", "");

      includeMethodsCode += `
  /**
   * Get a ${table.name} record by primary key with included related ${relationshipDesc}
   * @param pk - The primary key value${hasCompositePk ? 's' : ''}
   * @returns The record with nested ${method.path.join(' and ')} if found, null otherwise
   */
  async ${method.name}(pk: ${pkType}): Promise<${method.returnType}> {
    const results = await this.post<PaginatedResponse<${baseReturnType}>>(\`\${this.resource}/list\`, {
      where: ${pkWhere},
      include: ${JSON.stringify(method.includeSpec)},
      limit: 1
    });
    return (results.data[0] as ${baseReturnType}) ?? null;
  }
`;
    } else {
      includeMethodsCode += `
  /**
   * List ${table.name} records with included related ${relationshipDesc}
   * @param params - Query parameters (where, orderBy, order, limit, offset)
   * @returns Paginated results with nested ${method.path.join(' and ')} included
   */
  async ${method.name}(${baseParams}): Promise<${method.returnType}> {
    return this.post<${method.returnType}>(\`\${this.resource}/list\`, { ...params, include: ${JSON.stringify(method.includeSpec)} });
  }
`;
    }
  }

  return `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by PostgreSDK.
 * Any manual changes will be overwritten on the next generation.
 *
 * To make changes, modify your schema or configuration and regenerate.
 */
import { BaseClient } from "./base-client${ext}";
import type { Where } from "./where-types${ext}";
import type { PaginatedResponse } from "./types/shared${ext}";
${typeImports}
${otherTableImports.join("\n")}

/**
 * Helper type to merge JSONB type overrides into base types
 * @example
 * type UserWithMetadata = MergeJsonb<SelectUser, { metadata: { tags: string[] } }>;
 */
type MergeJsonb<TBase, TJsonb> = Omit<TBase, keyof TJsonb> & TJsonb;

/**
 * Client for ${table.name} table operations
 */
export class ${Type}Client extends BaseClient {
  private readonly resource = "/v1/${table.name}";

  /**
   * Create a new ${table.name} record
   * @param data - The data to insert
   * @returns The created record
   */
  async create(data: Insert${Type}): Promise<Select${Type}>;
  /**
   * Create a new ${table.name} record with JSONB type overrides
   * @param data - The data to insert
   * @returns The created record with typed JSONB fields
   * @example
   * type Metadata = { tags: string[]; prefs: { theme: 'light' | 'dark' } };
   * const user = await client.create<{ metadata: Metadata }>({ name: 'Alice', metadata: { tags: [], prefs: { theme: 'light' } } });
   */
  async create<TJsonb extends Partial<Select${Type}>>(
    data: MergeJsonb<Insert${Type}, TJsonb>
  ): Promise<MergeJsonb<Select${Type}, TJsonb>>;
  async create(data: any): Promise<any> {
    return this.post<any>(this.resource, data);
  }

  /**
   * Get a ${table.name} record by primary key
   * @param pk - The primary key value${hasCompositePk ? 's' : ''}
   * @returns The record if found, null otherwise
   */
  async getByPk(pk: ${pkType}): Promise<Select${Type} | null>;
  /**
   * Get a ${table.name} record by primary key with JSONB type overrides
   * @param pk - The primary key value${hasCompositePk ? 's' : ''}
   * @returns The record with typed JSONB fields if found, null otherwise
   */
  async getByPk<TJsonb extends Partial<Select${Type}>>(
    pk: ${pkType}
  ): Promise<MergeJsonb<Select${Type}, TJsonb> | null>;
  async getByPk(pk: ${pkType}): Promise<any> {
    const path = ${pkPathExpr};
    return this.get<any>(\`\${this.resource}/\${path}\`);
  }

  /**
   * List ${table.name} records with pagination and filtering
   * @param params - Query parameters
   * @param params.where - Filter conditions using operators like $eq, $gt, $in, $like, etc.
   * @param params.orderBy - Column(s) to sort by
   * @param params.order - Sort direction(s): "asc" or "desc"
   * @param params.limit - Maximum number of records to return (default: 50, max: 100)
   * @param params.offset - Number of records to skip for pagination
   * @param params.include - Related records to include (see listWith* methods for typed includes)
   * @returns Paginated results with data, total count, and hasMore flag
   */
  async list(params?: {
    include?: any;
    limit?: number;
    offset?: number;
    where?: Where<Select${Type}>;
    orderBy?: string | string[];
    order?: "asc" | "desc" | ("asc" | "desc")[];
  }): Promise<PaginatedResponse<Select${Type}>>;${hasVectorColumns ? `
  /**
   * List ${table.name} records with vector similarity search
   * @param params - Query parameters with vector search enabled
   * @param params.vector - Vector similarity search configuration
   * @returns Paginated results with _distance field included
   */
  async list(params: {
    include?: any;
    limit?: number;
    offset?: number;
    where?: Where<Select${Type}>;
    vector: {
      field: string;
      query: number[];
      metric?: "cosine" | "l2" | "inner";
      maxDistance?: number;
    };
    orderBy?: string | string[];
    order?: "asc" | "desc" | ("asc" | "desc")[];
  }): Promise<PaginatedResponse<Select${Type} & { _distance: number }>>;` : ""}
  /**
   * List ${table.name} records with pagination and filtering, with JSONB type overrides
   * @param params - Query parameters with typed JSONB fields in where clause
   * @returns Paginated results with typed JSONB fields
   */
  async list<TJsonb extends Partial<Select${Type}>>(params?: {
    include?: any;
    limit?: number;
    offset?: number;
    where?: Where<MergeJsonb<Select${Type}, TJsonb>>;${hasVectorColumns ? `
    vector?: {
      field: string;
      query: number[];
      metric?: "cosine" | "l2" | "inner";
      maxDistance?: number;
    };` : ""}
    orderBy?: string | string[];
    order?: "asc" | "desc" | ("asc" | "desc")[];
  }): Promise<PaginatedResponse<MergeJsonb<Select${Type}, TJsonb>>>;
  async list(params?: any): Promise<any> {
    return this.post<any>(\`\${this.resource}/list\`, params ?? {});
  }

  /**
   * Update a ${table.name} record by primary key
   * @param pk - The primary key value${hasCompositePk ? 's' : ''}
   * @param patch - Partial data to update
   * @returns The updated record if found, null otherwise
   */
  async update(pk: ${pkType}, patch: Update${Type}): Promise<Select${Type} | null>;
  /**
   * Update a ${table.name} record by primary key with JSONB type overrides
   * @param pk - The primary key value${hasCompositePk ? 's' : ''}
   * @param patch - Partial data to update with typed JSONB fields
   * @returns The updated record with typed JSONB fields if found, null otherwise
   */
  async update<TJsonb extends Partial<Select${Type}>>(
    pk: ${pkType},
    patch: MergeJsonb<Update${Type}, TJsonb>
  ): Promise<MergeJsonb<Select${Type}, TJsonb> | null>;
  async update(pk: ${pkType}, patch: any): Promise<any> {
    const path = ${pkPathExpr};
    return this.patch<any>(\`\${this.resource}/\${path}\`, patch);
  }

  /**
   * Delete a ${table.name} record by primary key
   * @param pk - The primary key value${hasCompositePk ? 's' : ''}
   * @returns The deleted record if found, null otherwise
   */
  async delete(pk: ${pkType}): Promise<Select${Type} | null>;
  /**
   * Delete a ${table.name} record by primary key with JSONB type overrides
   * @param pk - The primary key value${hasCompositePk ? 's' : ''}
   * @returns The deleted record with typed JSONB fields if found, null otherwise
   */
  async delete<TJsonb extends Partial<Select${Type}>>(
    pk: ${pkType}
  ): Promise<MergeJsonb<Select${Type}, TJsonb> | null>;
  async delete(pk: ${pkType}): Promise<any> {
    const path = ${pkPathExpr};
    return this.del<any>(\`\${this.resource}/\${path}\`);
  }
${includeMethodsCode}}
`;
}

export function emitClientIndex(tables: Table[], useJsExtensions?: boolean) {
  const ext = useJsExtensions ? ".js" : "";
  let out = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by PostgreSDK.
 * Any manual changes will be overwritten on the next generation.
 *
 * To make changes, modify your schema or configuration and regenerate.
 */
`;
  
  // Import auth types
  out += `import type { AuthConfig } from "./base-client${ext}";\n`;
  
  // Import all table clients
  for (const t of tables) {
    out += `import { ${pascal(t.name)}Client } from "./${t.name}${ext}";\n`;
  }
  
  // Export auth types
  out += `\nexport type { AuthConfig, HeaderMap, AuthHeadersProvider } from "./base-client${ext}";\n\n`;

  // SDK class
  out += `/**\n`;
  out += ` * Main SDK class that provides access to all table clients\n`;
  out += ` */\n`;
  out += `export class SDK {\n`;
  for (const t of tables) {
    out += `  public ${t.name}: ${pascal(t.name)}Client;\n`;
  }
  out += `\n  constructor(cfg: { baseUrl: string; fetch?: typeof fetch; auth?: AuthConfig }) {\n`;
  out += `    const f = cfg.fetch ?? fetch;\n`;
  for (const t of tables) {
    out += `    this.${t.name} = new ${pascal(t.name)}Client(cfg.baseUrl, f, cfg.auth);\n`;
  }
  out += `  }\n`;
  out += `}\n\n`;
  
  // Export base client for extension
  out += `export { BaseClient } from "./base-client${ext}";\n`;

  // Export IncludeSpec types for advanced usage
  out += `\n// Include specification types for custom queries\n`;
  out += `export type {\n`;
  for (const t of tables) {
    out += `  ${pascal(t.name)}IncludeSpec,\n`;
  }
  out += `} from "./include-spec${ext}";\n`;

  // Export Zod schemas
  out += `\n// Zod schemas for form validation\n`;
  for (const t of tables) {
    out += `export { Insert${pascal(t.name)}Schema, Update${pascal(t.name)}Schema } from "./zod/${t.name}${ext}";\n`;
  }

  // Export parameter schemas
  out += `\n// Zod schemas for query parameters\n`;
  out += `export { PaginationParamsSchema } from "./params/shared${ext}";\n`;
  for (const t of tables) {
    const Type = pascal(t.name);
    out += `export { ${Type}PkSchema, ${Type}ListParamsSchema, ${Type}OrderParamsSchema } from "./params/${t.name}${ext}";\n`;
  }

  // Export table types (Insert, Update, Select)
  out += `\n// Table types (Select, Insert, Update)\n`;
  for (const t of tables) {
    const Type = pascal(t.name);
    out += `export type { Insert${Type}, Update${Type}, Select${Type} } from "./types/${t.name}${ext}";\n`;
  }

  // Export shared types
  out += `\n// Shared types\n`;
  out += `export type { PaginatedResponse } from "./types/shared${ext}";\n`;

  return out;
}