import type { Graph } from "./rel-classify";

export function emitIncludeBuilder(graph: Graph, maxDepth: number) {
  return `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by PostgreSDK.
 * Any manual changes will be overwritten on the next generation.
 *
 * To make changes, modify your schema or configuration and regenerate.
 */
export const RELATION_GRAPH = ${JSON.stringify(graph, null, 2)} as const;
type TableName = keyof typeof RELATION_GRAPH;

export function buildWith(root: TableName, spec: any, maxDepth = ${maxDepth}) {
  return walk(root as string, spec, 0);
  function walk(table: string, s: any, depth: number): any {
    if (!s || depth >= maxDepth) return undefined;
    const rels: any = (RELATION_GRAPH as any)[table] || {};
    const out: any = {};
    for (const key of Object.keys(s)) {
      const rel = rels[key];
      if (!rel) throw new Error(\`Unknown include key '\${key}' on table '\${table}'\`);
      const v = s[key];
      if (v === true) out[key] = true;
      else if (v && typeof v === "object") {
        const child = walk(rel.target, v, depth + 1);
        out[key] = child ? { with: child } : true;
      }
    }
    return Object.keys(out).length ? out : undefined;
  }
}

export const buildWithFor = (t: TableName) =>
  (spec?: any, depth = ${maxDepth}) => (spec ? buildWith(t, spec, depth) : undefined);
`;
}
