/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by PostgreSDK.
 * Any manual changes will be overwritten on the next generation.
 *
 * To make changes, modify your schema or configuration and regenerate.
 */

/**
 * Type for inserting a new books record.
 * Fields with defaults or nullable columns are optional.
 */
export type InsertBooks = {
  id?: string;
  author_id?: string | null;
  title: string;
};

/**
 * Type for updating an existing books record.
 * All fields are optional, allowing partial updates.
 */
export type UpdateBooks = Partial<InsertBooks>;

/**
 * Type representing a books record from the database.
 * All fields are included as returned by SELECT queries.
 */
export type SelectBooks = {
  id: string;
  author_id: string | null;
  title: string;
};
