/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file was automatically generated by PostgreSDK.
 * Any manual changes will be overwritten on the next generation.
 *
 * To make changes, modify your schema or configuration and regenerate.
 */

/**
 * Type for inserting a new tags record.
 * Fields with defaults or nullable columns are optional.
 */
export type InsertTags = {
  id?: string;
  name: string;
};

/**
 * Type for updating an existing tags record.
 * All fields are optional, allowing partial updates.
 */
export type UpdateTags = Partial<InsertTags>;

/**
 * Type representing a tags record from the database.
 * All fields are included as returned by SELECT queries.
 */
export type SelectTags = {
  id: string;
  name: string;
};
